index:
  path:     /messages
  controller: App\Controller\DefaultController::index

index_chapter:
  path:     /messages/{chapter}
  controller: App\Controller\DefaultController::chapter

index_start_end:
  path:     /messages/{start}/{end}
  controller: App\Controller\DefaultController::index

titelei:
  path:     /titelei
  controller: App\Controller\DefaultController::titelei

footer:
  path:     /footer
  controller: App\Controller\DefaultController::footer

footer_offset:
  path:     /footer/{offset}
  controller: App\Controller\DefaultController::footer

header:
  path:     /header
  controller: App\Controller\DefaultController::header